# Generated by Django 5.1.1 on 2025-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0037_bankdetails_remove_userdata_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
