# Generated by Django 5.1.1 on 2025-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0038_remove_bankdetails_id_alter_bankdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user_id',
            field=models.CharField(max_length=25),
        ),
    ]
