# Generated by Django 5.1.1 on 2025-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0040_delete_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('bank_account', models.IntegerField(blank=True, default=0, null=True)),
                ('ifsc_code', models.CharField(blank=True, default='SBIN0989054', max_length=15, null=True)),
                ('upi_id', models.CharField(blank=True, default='upi_id.oksbi', max_length=15, null=True)),
            ],
        ),
    ]
