# Generated by Django 5.1.1 on 2025-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0042_devtransactions_alter_bankdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='caste_Sub',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
