# Generated by Django 5.1.1 on 2025-07-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0043_userdata_caste_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='caste_Sub',
            new_name='sub_caste',
        ),
    ]
