# Generated by Django 5.1.1 on 2025-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0045_userdata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
