# Generated by Django 5.1.1 on 2025-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0046_alter_userdata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='family_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='family_values',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
