# Generated by Django 5.1.1 on 2025-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0047_userdata_family_status_userdata_family_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suceess_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('discription', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
