# Generated by Django 5.1.1 on 2025-07-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0048_suceess_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suceess_story',
            name='discription',
        ),
        migrations.AddField(
            model_name='suceess_story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
