# Generated by Django 5.1.1 on 2025-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0049_remove_suceess_story_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
