# Generated by Django 5.1.1 on 2025-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0050_userdata_place_userdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='contact_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='mother_tongue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='no_of_children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
