# Generated by Django 5.1.1 on 2025-07-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0051_userdata_annual_income_userdata_contact_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='annual_income',
        ),
    ]
