# Generated by Django 5.1.1 on 2025-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0052_remove_userdata_annual_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='sub_caste',
            new_name='subcaste',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='family_status',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='family_values',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='income_range',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='no_of_children',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='place',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='time',
        ),
        migrations.AddField(
            model_name='userdata',
            name='contact1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
