# Generated by Django 5.1.1 on 2025-07-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0053_rename_sub_caste_userdata_subcaste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='mobile_no',
        ),
    ]
