# Generated by Django 5.1.1 on 2025-07-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0055_devtransactions_ifsc_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Suceess_Story',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(blank=True, default='SBIN0989054', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, default='upi_id.oksbi', max_length=15, null=True),
        ),
    ]
