# Generated by Django 5.1.1 on 2025-07-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0056_delete_bankdetails_delete_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtransactions',
            old_name='user_id',
            new_name='dev_id',
        ),
    ]
