# Generated by Django 5.1.1 on 2025-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0057_rename_user_id_devtransactions_dev_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='User_cover_pic'),
        ),
    ]
