# Generated by Django 5.1.1 on 2025-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0058_alter_userdata_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bank_account',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ifsc_code',
            field=models.CharField(blank=True, default='SBIN0989054', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='upi_id',
            field=models.CharField(blank=True, default='upi_id.oksbi', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devtransactions',
            name='bank_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='devtransactions',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stafftransactions',
            name='bank_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='stafftransactions',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='contact1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='bank_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
