# Generated by Django 5.1.1 on 2025-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0060_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtransactions',
            name='UTI',
            field=models.CharField(default='UPI Transaction Id', max_length=15),
        ),
        migrations.AddField(
            model_name='stafftransactions',
            name='UTI',
            field=models.CharField(default='UPI Transaction Id', max_length=15),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='UTI',
            field=models.CharField(default='UPI Transaction Id', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, default='Account Number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, default='User_cover_pic/flowers-background.jpg', null=True, upload_to='User_cover_pic'),
        ),
    ]
