# Generated by Django 5.1.1 on 2025-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0063_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Hobbies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Lifestyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='created_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
