# Generated by Django 5.1.1 on 2025-09-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0064_userdata_hobbies_userdata_lifestyle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
