# Generated by Django 5.1.1 on 2025-09-21 07:16

import risteyapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0065_alter_userdata_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.CharField(default=risteyapp.utils.secure_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
