# Generated by Django 5.1.1 on 2025-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0066_rechargeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcharges',
            name='user_re_com',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcharges',
            name='post_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcharges',
            name='staff_commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
