# Generated by Django 5.1.1 on 2025-09-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0069_phoneotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone',
            new_name='contact',
        ),
    ]
