# Generated by Django 5.1.1 on 2025-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0070_rename_phone_phoneotp_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.CharField(max_length=5),
        ),
    ]
