# Generated by Django 5.1.1 on 2025-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0071_alter_userdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.CharField(max_length=10),
        ),
    ]
