# Generated by Django 5.1.1 on 2025-10-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0072_alter_userdata_address_alter_userdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, default='User_cover_pic/floral-ornaments_ZsX1vQs.jpg', null=True, upload_to='User_cover_pic'),
        ),
    ]
