# Generated by Django 5.1.1 on 2025-10-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0073_alter_userdata_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disttrict',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='disttrict',
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='userdata',
            name='district',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='stafftransactions',
            name='UTI',
            field=models.CharField(default='UPI Transaction Id', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, default='Account Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(blank=True, default='SBIN0989054', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, default='upi_id.oksbi', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bank_account',
            field=models.CharField(blank=True, default='0000000000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='caste',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ifsc_code',
            field=models.CharField(blank=True, default='SBIN0989054', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mother_tongue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='subcaste',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='upi_id',
            field=models.CharField(blank=True, default='upi_id.oksbi', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
