# Generated by Django 5.1.1 on 2025-07-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0039_bankdetails_id_alter_bankdetails_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
